docs:
  - changed-files:
      - any-glob-to-any-file: docs/**

migration:
  - changed-files:
      - any-glob-to-any-file: src/**/migrations/**/*.py

upstream dependency:
  - changed-files:
      - any-glob-to-any-file: 
        - requirements/requirements.txt
        - requirements/requirements-client.txt
        - requirements/requirements-dev.txt

2.x:
  - base-branch: '2.x'
