name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Syntask
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        If you are new to Syntask bug reports, please review our many examples of [well written bug reports](https://github.com/synopkg/syntask/issues?q=is%3Aissue+label%3A%22great+writeup%22). 
        Each of these reports include the following features:

        1. A succinct description of the problem. 

        2. A succinct code example which reproduces the problem, otherwise known as a [minimal reproducible example](https://stackoverflow.com/help/mcve).

        3. The complete stack traces for errors - please avoid screenshots, and use markdown formatted text inside issues.

        4. Additional details that may help us reproduce your issue.


        For usage questions, please check out Syntask's [Community Slack](https://www.syntask.khulnasoft.com/slack/).

  - type: textarea
    attributes:
      label: Bug summary
      description: A clear and concise description of what the bug is, ideally including [a minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: >
        An explanation of the behavior, along with code that will help others reproduce the issue:

          ```python
          from syntask import flow

          @flow
          def my_flow():
            raise ValueError("This flow misbehaves every time it's run and I don't know why!")
          ```

          Please include tracebacks, console output, etc. with code formatting.

    validations:
      required: true

  - type: textarea
    attributes:
      label: Version info (`syntask version` output)
      description: >
        Provide information about your Syntask version and environment. The easiest way to retrieve all of this information is by running the `syntask version` command.
      placeholder: "# Copy output of the `syntask version` command here. Do not just include your Syntask version number."
      render: Text
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here, including screenshots for UI issues.
    validations:
      required: false

  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to submit a bug report!
