name: Verify syntask-client build

on:
  pull_request:
    branches:
      - main
    paths:
      - client/*
      - src/syntask/**/*.py
      - requirements.txt
      - requirements-client.txt
      - setup.cfg
      - .github/workflows/syntask-client.yaml
  push:
    branches:
      - main
    paths:
      - client/*
      - src/syntask/**/*.py
      - requirements.txt
      - requirements-client.txt
      - setup.cfg
      - .github/workflows/syntask-client.yaml
  workflow_call:
    inputs:
      upload-artifacts:
        description: "Whether or not to upload artifacts created in this workflow"
        default: false
        type: boolean
      artifact-name:
        description: "The name for the build syntask-client artifact"
        default: "syntask-client-pypi-dists"
        type: string

jobs:
  syntask-client-smoke-test:
    name: Build and run syntask-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Versioneer only generates correct versions with a full fetch
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "requirements-client.txt"

      - name: Create a temp dir to stage our build
        run: echo "TMPDIR=$(mktemp -d)" >> $GITHUB_ENV

      - name: Prepare files for syntask-client build (omit the local build)
        run: sh client/build_client.sh
        env:
          TMPDIR: ${{ env.TMPDIR }}

      - name: Build a binary wheel and a source tarball
        run: pip install wheel && python setup.py sdist bdist_wheel
        working-directory: ${{ env.TMPDIR }}

      - name: Install the built client from the locally built package
        run: pip install dist/*.tar.gz
        working-directory: ${{ env.TMPDIR }}

      - name: Get the version of built `syntask-client`
        run: |
          syntask_client_version=$(python -c "import syntask; print(syntask.__version__)")
          echo "syntask_client_version=$syntask_client_version" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TMPDIR }}
        id: syntask_client_version

      - name: Run the smoke test flow using the built client
        run: python client/client_flow.py
        working-directory: ${{ env.TMPDIR }}
        env:
          SYNTASK_API_KEY: ${{ secrets.SYNTASK_CLIENT_SA_API_KEY }}
          SYNTASK_API_URL: "https://api.syntask.cloud/api/accounts/9b649228-0419-40e1-9e0d-44954b5c0ab6/workspaces/96bd3cf8-85c9-4545-9713-b4e3c3e03466" # sandbox, syntask-client workspace

      - name: Install syntask from source
        run: pip install .

      - name: Get the version of built `syntask`
        run: |
          syntask_version=$(syntask --version)
          echo "syntask_version=$syntask_version" >> $GITHUB_OUTPUT
        id: syntask_version

      - name: Verify that the built `syntask` and `syntask-client` versions are the same
        run: |
          if [ "${{ steps.syntask_version.outputs.syntask_version }}" != "${{ steps.syntask_client_version.outputs.syntask_client_version }}" ]; then
            echo "The built versions of syntask and syntask-client are not the same."
            exit 1
          fi

      - name: Run the smoke test flow again with syntask and syntask-client installed
        run: python client/client_flow.py
        working-directory: ${{ env.TMPDIR }}
        env:
          SYNTASK_API_KEY: ${{ secrets.SYNTASK_CLIENT_SA_API_KEY }}
          SYNTASK_API_URL: "https://api.syntask.cloud/api/accounts/9b649228-0419-40e1-9e0d-44954b5c0ab6/workspaces/96bd3cf8-85c9-4545-9713-b4e3c3e03466" # sandbox, syntask-client workspace

      - name: Publish build artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: "${{ env.TMPDIR }}/dist"
